# **Linear Regression**

In [1]:
import numpy as np
#a_and_b = np.array([3.4, 77]) # a and b
a = 3.4
b = 77
data = np.array([[2, 81], [4, 93], [6, 91], [8, 97]])
train_x = data[:, 0]
train_y = data[:, 1]

In [2]:
print(data)

[[ 2 81]
 [ 4 93]
 [ 6 91]
 [ 8 97]]


In [3]:
print(train_x)
print(train_y)

[2 4 6 8]
[81 93 91 97]


In [ ]:
print(a * train_x + b)

[ 83.8  90.6  97.4 104.2]


In [ ]:
mse = sum(((a * train_x + b) - train_y)**2)/len(train_x)
print(mse)

26.60000000000003
